// This file is automatically generated from your CSS. Any edits will be overwritten.
export const bar: string;
export const barCell: string;
export const leftCol: string;
export const rightCol: string;
